### ISSUE TITLE
vm.tiktok.com/{ID} links no longer working?

### ISSUE THREAD

**Issue by MrMaou** [dustinrouillard/tiktok-embeds#3]
Changing 
from https://vm.tiktok.com/ZT8WXquk6/ 
to https://vm.dstn.to/ZT8WXquk6/ is now giving a "invalid_match_for_video" error

However, changing:
https://www.tiktok.com/@mikecakez/video/7329968713464073518 
to
https://vm.dstn.to/@mikecakez/video/7329968713464073518 
is working just fine

**Comment by dustinrouillard** [comment]
Fixed, at latest for now, we'll see if it works for everything and for how long. https://github.com/dustinrouillard/tiktok-embeds/commit/5f2bda85585a16e4e162aaa29eb11c5ffc66b836
